name: Push

on: push

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v1
        env:
          cache-name: node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: Install Dependencies
        run: npm ci

      - name: Run eslint-check and generate report
        id: eslint-check
        run: |
          npm run eslint-check -- --output-file eslint_report.json --format json
        continue-on-error: true

      - name: Annotate Lint Results
        uses: ataylorme/eslint-annotate-action@1.0.4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          report-json: eslint_report.json
        continue-on-error: true

      - name: Check eslint-check outcome
        if: steps.eslint-check.outcome != 'success'
        run: |
          echo "::error::eslint-check failed. View output of _Run eslint-check and generate report_ step"
          exit 1

      - name: Run Repolinter
          uses: newrelic/repolinter-action@v1
          with:
            config_url: https://raw.githubusercontent.com/newrelic/.github/main/repolinter-rulesets/community-plus.yml
            output_type: issue

  build:
    name: Build and test
    needs: eslint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Cache node_modules
        id: cache-node-modules
        uses: actions/cache@v1
        env:
          cache-name: node-modules
        with:
          path: ~/.npm
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

